name: Update output.json

on:
  schedule:
    - cron: '31 5 * * *' # Once per day, random time
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './scripts/update'
    steps:
      - name: Checkout self
        uses: actions/checkout@v2

      - name: Checkout vcpkg
        uses: actions/checkout@v2
        with:
          repository: 'microsoft/vcpkg'
          path: 'vcpkg'

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - run: npm ci

      - run: npm run start $GITHUB_WORKSPACE/vcpkg

      - uses: actions/upload-artifact@v2
        with:
          name: 'output.json'
          path: './output.json'
